notifications:
  email: false

language: node_js

node_js:
  - 6.2.2

services:
  - mongodb

before_install:
  - sudo apt-get update -qq

install:
  - cd app
  - npm install
  - npm start
  - ^X

script: 
  - mocha

